### ISSUE TITLE
Basic functionality checklist

### ISSUE THREAD

**Issue by jurplel** [jurplel/kimageformats-binaries#1]
- [x] kf5archive not working on linux
- [x] HEIF not working on linux
- [x] windows not working

**Comment by g4x86** [comment]
As of today 7/14, the binary builds deb/rpm/flatpak on Linux don't support HEIF format (tested on Ubuntu 22.04), and the only EXCEPTION is the AppImage version which magically can view HEIF/HEIC files.
